name       : protontricks
version    : 1.8.0
release    : 14
source     :
    - git|https://github.com/Matoking/protontricks.git : 1.8.0
homepage   : https://github.com/Matoking/protontricks
license    : GPL-3.0-or-later
component  : virt
summary    : A simple wrapper that does winetricks things for Proton enabled games
description: |
    A simple wrapper that does winetricks things for Proton enabled games
builddeps  :
    - python-setuptools-scm
    - python-vdf
rundeps    :
    - python-vdf
    - winetricks
    - yad
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
